/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as PromessasRouteImport } from './routes/promessas'
import { Route as PromessaOuFumoRouteImport } from './routes/promessa-ou-fumo'
import { Route as PartidosRouteImport } from './routes/partidos'
import { Route as MetodologiaRouteImport } from './routes/metodologia'
import { Route as EvidenciasRouteImport } from './routes/evidencias'
import { Route as EticaRouteImport } from './routes/etica'
import { Route as EleicoesRouteImport } from './routes/eleicoes'
import { Route as DocumentosRouteImport } from './routes/documentos'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ComparadorRouteImport } from './routes/comparador'
import { Route as BuscaRouteImport } from './routes/busca'
import { Route as AnaliseIdeologicaRouteImport } from './routes/analise-ideologica'
import { Route as IndexRouteImport } from './routes/index'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const PromessasRoute = PromessasRouteImport.update({
  id: '/promessas',
  path: '/promessas',
  getParentRoute: () => rootRouteImport,
} as any)
const PromessaOuFumoRoute = PromessaOuFumoRouteImport.update({
  id: '/promessa-ou-fumo',
  path: '/promessa-ou-fumo',
  getParentRoute: () => rootRouteImport,
} as any)
const PartidosRoute = PartidosRouteImport.update({
  id: '/partidos',
  path: '/partidos',
  getParentRoute: () => rootRouteImport,
} as any)
const MetodologiaRoute = MetodologiaRouteImport.update({
  id: '/metodologia',
  path: '/metodologia',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenciasRoute = EvidenciasRouteImport.update({
  id: '/evidencias',
  path: '/evidencias',
  getParentRoute: () => rootRouteImport,
} as any)
const EticaRoute = EticaRouteImport.update({
  id: '/etica',
  path: '/etica',
  getParentRoute: () => rootRouteImport,
} as any)
const EleicoesRoute = EleicoesRouteImport.update({
  id: '/eleicoes',
  path: '/eleicoes',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentosRoute = DocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparadorRoute = ComparadorRouteImport.update({
  id: '/comparador',
  path: '/comparador',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscaRoute = BuscaRouteImport.update({
  id: '/busca',
  path: '/busca',
  getParentRoute: () => rootRouteImport,
} as any)
const AnaliseIdeologicaRoute = AnaliseIdeologicaRouteImport.update({
  id: '/analise-ideologica',
  path: '/analise-ideologica',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analise-ideologica': typeof AnaliseIdeologicaRoute
  '/busca': typeof BuscaRoute
  '/comparador': typeof ComparadorRoute
  '/dashboard': typeof DashboardRoute
  '/documentos': typeof DocumentosRoute
  '/eleicoes': typeof EleicoesRoute
  '/etica': typeof EticaRoute
  '/evidencias': typeof EvidenciasRoute
  '/metodologia': typeof MetodologiaRoute
  '/partidos': typeof PartidosRoute
  '/promessa-ou-fumo': typeof PromessaOuFumoRoute
  '/promessas': typeof PromessasRoute
  '/relatorios': typeof RelatoriosRoute
  '/sobre': typeof SobreRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analise-ideologica': typeof AnaliseIdeologicaRoute
  '/busca': typeof BuscaRoute
  '/comparador': typeof ComparadorRoute
  '/dashboard': typeof DashboardRoute
  '/documentos': typeof DocumentosRoute
  '/eleicoes': typeof EleicoesRoute
  '/etica': typeof EticaRoute
  '/evidencias': typeof EvidenciasRoute
  '/metodologia': typeof MetodologiaRoute
  '/partidos': typeof PartidosRoute
  '/promessa-ou-fumo': typeof PromessaOuFumoRoute
  '/promessas': typeof PromessasRoute
  '/relatorios': typeof RelatoriosRoute
  '/sobre': typeof SobreRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analise-ideologica': typeof AnaliseIdeologicaRoute
  '/busca': typeof BuscaRoute
  '/comparador': typeof ComparadorRoute
  '/dashboard': typeof DashboardRoute
  '/documentos': typeof DocumentosRoute
  '/eleicoes': typeof EleicoesRoute
  '/etica': typeof EticaRoute
  '/evidencias': typeof EvidenciasRoute
  '/metodologia': typeof MetodologiaRoute
  '/partidos': typeof PartidosRoute
  '/promessa-ou-fumo': typeof PromessaOuFumoRoute
  '/promessas': typeof PromessasRoute
  '/relatorios': typeof RelatoriosRoute
  '/sobre': typeof SobreRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analise-ideologica'
    | '/busca'
    | '/comparador'
    | '/dashboard'
    | '/documentos'
    | '/eleicoes'
    | '/etica'
    | '/evidencias'
    | '/metodologia'
    | '/partidos'
    | '/promessa-ou-fumo'
    | '/promessas'
    | '/relatorios'
    | '/sobre'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analise-ideologica'
    | '/busca'
    | '/comparador'
    | '/dashboard'
    | '/documentos'
    | '/eleicoes'
    | '/etica'
    | '/evidencias'
    | '/metodologia'
    | '/partidos'
    | '/promessa-ou-fumo'
    | '/promessas'
    | '/relatorios'
    | '/sobre'
  id:
    | '__root__'
    | '/'
    | '/analise-ideologica'
    | '/busca'
    | '/comparador'
    | '/dashboard'
    | '/documentos'
    | '/eleicoes'
    | '/etica'
    | '/evidencias'
    | '/metodologia'
    | '/partidos'
    | '/promessa-ou-fumo'
    | '/promessas'
    | '/relatorios'
    | '/sobre'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnaliseIdeologicaRoute: typeof AnaliseIdeologicaRoute
  BuscaRoute: typeof BuscaRoute
  ComparadorRoute: typeof ComparadorRoute
  DashboardRoute: typeof DashboardRoute
  DocumentosRoute: typeof DocumentosRoute
  EleicoesRoute: typeof EleicoesRoute
  EticaRoute: typeof EticaRoute
  EvidenciasRoute: typeof EvidenciasRoute
  MetodologiaRoute: typeof MetodologiaRoute
  PartidosRoute: typeof PartidosRoute
  PromessaOuFumoRoute: typeof PromessaOuFumoRoute
  PromessasRoute: typeof PromessasRoute
  RelatoriosRoute: typeof RelatoriosRoute
  SobreRoute: typeof SobreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promessas': {
      id: '/promessas'
      path: '/promessas'
      fullPath: '/promessas'
      preLoaderRoute: typeof PromessasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promessa-ou-fumo': {
      id: '/promessa-ou-fumo'
      path: '/promessa-ou-fumo'
      fullPath: '/promessa-ou-fumo'
      preLoaderRoute: typeof PromessaOuFumoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partidos': {
      id: '/partidos'
      path: '/partidos'
      fullPath: '/partidos'
      preLoaderRoute: typeof PartidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metodologia': {
      id: '/metodologia'
      path: '/metodologia'
      fullPath: '/metodologia'
      preLoaderRoute: typeof MetodologiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidencias': {
      id: '/evidencias'
      path: '/evidencias'
      fullPath: '/evidencias'
      preLoaderRoute: typeof EvidenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/etica': {
      id: '/etica'
      path: '/etica'
      fullPath: '/etica'
      preLoaderRoute: typeof EticaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eleicoes': {
      id: '/eleicoes'
      path: '/eleicoes'
      fullPath: '/eleicoes'
      preLoaderRoute: typeof EleicoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentos': {
      id: '/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof DocumentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparador': {
      id: '/comparador'
      path: '/comparador'
      fullPath: '/comparador'
      preLoaderRoute: typeof ComparadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/busca': {
      id: '/busca'
      path: '/busca'
      fullPath: '/busca'
      preLoaderRoute: typeof BuscaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analise-ideologica': {
      id: '/analise-ideologica'
      path: '/analise-ideologica'
      fullPath: '/analise-ideologica'
      preLoaderRoute: typeof AnaliseIdeologicaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnaliseIdeologicaRoute: AnaliseIdeologicaRoute,
  BuscaRoute: BuscaRoute,
  ComparadorRoute: ComparadorRoute,
  DashboardRoute: DashboardRoute,
  DocumentosRoute: DocumentosRoute,
  EleicoesRoute: EleicoesRoute,
  EticaRoute: EticaRoute,
  EvidenciasRoute: EvidenciasRoute,
  MetodologiaRoute: MetodologiaRoute,
  PartidosRoute: PartidosRoute,
  PromessaOuFumoRoute: PromessaOuFumoRoute,
  PromessasRoute: PromessasRoute,
  RelatoriosRoute: RelatoriosRoute,
  SobreRoute: SobreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
